# Generated by Django 4.0.5 on 2022-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_region_post_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cultivation',
            field=models.CharField(default='tomato', max_length=255),
        ),
    ]
