# Generated by Django 4.0.5 on 2022-09-18 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_post_post_time_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateField(verbose_name=datetime.datetime(2022, 9, 18, 11, 59, 34, 902377)),
        ),
    ]
