# Generated by Django 4.0.5 on 2022-09-18 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_alter_post_post_date_alter_post_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='alertlevel',
            field=models.CharField(default='red', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
