# Generated by Django 4.0.5 on 2022-09-18 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_alertlevel_post_alertlevel_alter_post_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
