# Generated by Django 4.0.5 on 2022-09-18 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
